#!/bin/bash

# script only runs on Linux

modprobe tun
sleep 10
chown admin /dev/net/tun
chown admin .tkenvrc
#echo 1 > /proc/sys/net/ipv4/ip_forward
sleep 10
../../src/OverSim -u Cmdenv -f world.ini &
#../../src/OverSim -f world.ini &
sleep 10
ifconfig tun0 10.0.0.1 netmask 255.0.0.0 up
echo "tun0 up done"
route add -net 11.0.0.0 netmask 255.0.0.0 dev tun0
route add -net 12.0.0.0 netmask 255.0.0.0 dev tun0
route add -net 13.0.0.0 netmask 255.0.0.0 dev tun0
