//
// Generated file, do not edit! Created by opp_msgc 4.1 from underlay/simpleunderlay/SimpleUDPPacket.msg.
//

#ifndef _SIMPLEUDPPACKET_M_H_
#define _SIMPLEUDPPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "INETDefs.h"
// }}



/**
 * Class generated from <tt>underlay/simpleunderlay/SimpleUDPPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet SimpleUDPPacket
 * {
 *         int sourcePort = -1;    
 *         int destinationPort = -1;    
 * }
 * </pre>
 */
class SimpleUDPPacket : public ::cPacket
{
  protected:
    int sourcePort_var;
    int destinationPort_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SimpleUDPPacket&);

  public:
    SimpleUDPPacket(const char *name=NULL, int kind=0);
    SimpleUDPPacket(const SimpleUDPPacket& other);
    virtual ~SimpleUDPPacket();
    SimpleUDPPacket& operator=(const SimpleUDPPacket& other);
    virtual SimpleUDPPacket *dup() const {return new SimpleUDPPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSourcePort() const;
    virtual void setSourcePort(int sourcePort_var);
    virtual int getDestinationPort() const;
    virtual void setDestinationPort(int destinationPort_var);
};

inline void doPacking(cCommBuffer *b, SimpleUDPPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SimpleUDPPacket& obj) {obj.parsimUnpack(b);}


#endif // _SIMPLEUDPPACKET_M_H_
