//
// Generated file, do not edit! Created by opp_msgc 4.0 from transport/udp/UDPPacket.msg.
//

#ifndef _UDPPACKET_M_H_
#define _UDPPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0400
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API 
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API 
#  endif
#endif

// cplusplus {{ ... }} section:

#include "INETDefs.h"
// end cplusplus



/**
 * Class generated from <tt>transport/udp/UDPPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet UDPPacket
 * {
 *     int sourcePort = -1;
 *     int destinationPort = -1;
 * }
 * </pre>
 */
class INET_API UDPPacket : public cPacket
{
  protected:
    int sourcePort_var;
    int destinationPort_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UDPPacket&);

  public:
    UDPPacket(const char *name=NULL, int kind=0);
    UDPPacket(const UDPPacket& other);
    virtual ~UDPPacket();
    UDPPacket& operator=(const UDPPacket& other);
    virtual UDPPacket *dup() const {return new UDPPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSourcePort() const;
    virtual void setSourcePort(int sourcePort_var);
    virtual int getDestinationPort() const;
    virtual void setDestinationPort(int destinationPort_var);
};

inline void doPacking(cCommBuffer *b, UDPPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, UDPPacket& obj) {obj.parsimUnpack(b);}


#endif // _UDPPACKET_M_H_
