//
// Generated file, do not edit! Created by opp_msgc 4.0 from transport/rtp/RTPSenderStatusMessage.msg.
//

#ifndef _RTPSENDERSTATUSMESSAGE_M_H_
#define _RTPSENDERSTATUSMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0400
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API 
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API 
#  endif
#endif

// cplusplus {{ ... }} section:

#include "INETDefs.h"
// end cplusplus



/**
 * Class generated from <tt>transport/rtp/RTPSenderStatusMessage.msg</tt> by opp_msgc.
 * <pre>
 * packet RTPSenderStatusMessage
 * {
 *     string status;
 *     uint32 timeStamp;
 * };
 * </pre>
 */
class INET_API RTPSenderStatusMessage : public cPacket
{
  protected:
    opp_string status_var;
    uint32 timeStamp_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RTPSenderStatusMessage&);

  public:
    RTPSenderStatusMessage(const char *name=NULL, int kind=0);
    RTPSenderStatusMessage(const RTPSenderStatusMessage& other);
    virtual ~RTPSenderStatusMessage();
    RTPSenderStatusMessage& operator=(const RTPSenderStatusMessage& other);
    virtual RTPSenderStatusMessage *dup() const {return new RTPSenderStatusMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getStatus() const;
    virtual void setStatus(const char * status_var);
    virtual uint32 getTimeStamp() const;
    virtual void setTimeStamp(uint32 timeStamp_var);
};

inline void doPacking(cCommBuffer *b, RTPSenderStatusMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RTPSenderStatusMessage& obj) {obj.parsimUnpack(b);}


#endif // _RTPSENDERSTATUSMESSAGE_M_H_
