//
// Generated file, do not edit! Created by opp_msgc 4.0 from linklayer/mfcore/TransmComplete.msg.
//

#ifndef _TRANSMCOMPLETE_M_H_
#define _TRANSMCOMPLETE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0400
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API 
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API 
#  endif
#endif

// cplusplus {{ ... }} section:

#include "INETDefs.h"
// end cplusplus



/**
 * Class generated from <tt>linklayer/mfcore/TransmComplete.msg</tt> by opp_msgc.
 * <pre>
 * packet TransmComplete
 * {
 * }
 * </pre>
 */
class INET_API TransmComplete : public cPacket
{
  protected:

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TransmComplete&);

  public:
    TransmComplete(const char *name=NULL, int kind=0);
    TransmComplete(const TransmComplete& other);
    virtual ~TransmComplete();
    TransmComplete& operator=(const TransmComplete& other);
    virtual TransmComplete *dup() const {return new TransmComplete(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, TransmComplete& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TransmComplete& obj) {obj.parsimUnpack(b);}


#endif // _TRANSMCOMPLETE_M_H_
